<a href="https://colab.research.google.com/github/shafeeqshahar/PyTorch-Tutorial-Youtube/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSOR

In [1]:
import torch
import numpy as np

In [2]:
my_tensor = torch.randn(2, 3, 4)
my_tensor

tensor([[[-1.0907,  0.0328, -0.0362,  1.0750],
         [-1.2903,  0.3835,  0.9833,  0.8693],
         [-0.9528,  0.2755, -1.0348, -1.0075]],

        [[ 0.7431, -0.6565,  0.7945,  1.2589],
         [ 0.5433, -0.8834, -0.3489,  1.0443],
         [-0.3241, -0.7572,  0.8564, -0.2165]]])

# TENSOR OPS

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
my_torch = my_torch.reshape(-1, 2)

In [12]:
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [13]:
my_torch3 = torch.arange(15)
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [14]:
my_torch4 = my_torch3.view(3, 5)
my_torch4

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [16]:
my_torch3[1] = 4141

In [17]:
my_torch4

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14]])

In [22]:
my_torch4[2, :]

tensor([10, 11, 12, 13, 14])