<a href="https://colab.research.google.com/github/shafeeqshahar/PyTorch-Tutorial-Youtube/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSOR

In [1]:
import torch
import numpy as np

In [2]:
my_tensor = torch.randn(2, 3, 4)
my_tensor

tensor([[[ 1.7275, -1.6168,  0.7697,  0.7560],
         [-0.3531,  0.8818,  0.7542,  0.4530],
         [-1.9107,  1.9261,  0.1336, -1.3162]],

        [[ 0.3170, -1.1445,  0.3549,  1.3823],
         [ 0.5308, -1.5677, -0.9683, -0.0555],
         [ 0.5819,  0.5633,  0.1855, -1.0825]]])

# TENSOR OPS

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_torch = my_torch.reshape(-1, 2)

In [5]:
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [6]:
my_torch3 = torch.arange(15)
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
my_torch4 = my_torch3.view(3, 5)
my_torch4

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [8]:
my_torch3[1] = 4141

In [9]:
my_torch4

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14]])

In [10]:
my_torch4[2, :]

tensor([10, 11, 12, 13, 14])

# TENSOR MATH OPS

In [11]:
tensor_A = torch.tensor([1, 2, 3, 4])
tensor_B = torch.tensor([5, 6, 7, 8])

In [12]:
tensor_A + tensor_B

tensor([ 6,  8, 10, 12])

In [13]:
tensor_A.add_(tensor_B)
tensor_A

tensor([ 6,  8, 10, 12])